SELECT TOP 1 
	D3_NUMSEQ 
FROM 
	SD3010  
WHERE 
	D3_FILIAL = '01' 
	AND D3_OP = '000028' 
	AND D3_COD = '000001' 
	AND D3_LOCAL = '01' 
	AND D3_CF = 'PR0' 
ORDER BY 
	R_E_C_N_O_ DESC; 

----//----

SELECT 
	C9_FILIAL, 
	C9_PEDIDO, 
	C9_CLIENTE, 
	C9_LOJA, 
	A1_NOME, 
	C9_DATENT, 
	C9_ITEM, 
	C9_SEQUEN, 
	C9_PRODUTO, 
	B1_DESC, 
	C9_LOCAL, 
	C9_LOTECTL, 
	COALESCE(DC_LOCALIZ, '') AS PRD_ENDERE, 
	A1_END AS CLI_ENDERE, 
	A1_MUN, 
	YA_DESCR, 
	CASE 
		WHEN TRIM(C9_NUMSERI) = '' THEN DC_NUMSERI ELSE C9_NUMSERI 
	END AS NUMSERI, 
	C9_QTDLIB, 
	C9_QTDLIB * B1_M3 AS VOLUME, 
	CASE 
		WHEN C9_ZCENARI = '' AND C9_ZDRIVIN IS NULL THEN 1 
		WHEN C9_ZCENARI <> '' AND C9_ZDRIVIN IS NULL THEN 2 
		WHEN C9_ZCENARI <> '' AND C9_ZDRIVIN IS NOT NULL THEN 2 
		WHEN C9_ZCENARI = '' AND C9_ZDRIVIN IS NOT NULL THEN 4 
	END AS COMUNIC, 
	C9_DATENT || C9_CLIENTE || C9_PEDIDO || C9_ITEM || C9_SEQUEN AS REC, 
	'' AS SEL_OK 
FROM 
	SC9010 C9 
	INNER JOIN 
		SC5010 C5 
		ON C9.C9_FILIAL = C5.C5_FILIAL 
		AND C9_PEDIDO = C5_NUM 
		AND C5.D_E_L_E_T_ = '' 
	INNER JOIN 
		SB1010 B1 
		ON B1.B1_FILIAL = ' '  
		AND B1_COD = C9_PRODUTO 
		AND B1.D_E_L_E_T_ = '' 
	INNER JOIN 
		SA1010 A1 
		ON A1.A1_FILIAL = ' '  
		AND A1_COD = C9_CLIENTE 
		AND A1.D_E_L_E_T_ = '' 
	INNER JOIN 
		SYA010 YA 
		ON YA.YA_FILIAL = ' '  
		AND YA_CODGI = A1_PAIS 
		AND YA.D_E_L_E_T_ = '' 
	LEFT JOIN 
		SDC010 DC 
		ON C9.C9_FILIAL = DC.DC_FILIAL 
		AND DC_PRODUTO = C9_PRODUTO 
		AND C9_LOCAL = DC_LOCAL 
		AND DC_ORIGEM = 'SC6' 
		AND DC_PEDIDO = C9_PEDIDO 
		AND DC_ITEM = C9_ITEM 
		AND DC_SEQ = C9_SEQUEN 
		AND DC_LOTECTL = C9_LOTECTL 
		AND DC_NUMLOTE = C9_NUMLOTE 
		AND DC.D_E_L_E_T_ = '' 
WHERE 
	C9_FILIAL = '01' 
	AND C9_PEDIDO BETWEEN '' AND 'ZZZZZZ' 
	AND C9_CLIENTE BETWEEN '' AND 'ZZZZZZ' 
	AND C9_LOJA BETWEEN '' AND 'ZZ' 
	AND C9_DATENT BETWEEN '20260811' AND '20491231' 
	AND C9_PRODUTO BETWEEN '' AND 'ZZZZZZZZZZZZZZZ' 
	AND C9_BLEST = '' 
	AND C9_BLCRED = '' 
	AND C9.D_E_L_E_T_ = '' 
ORDER BY 
	C9_PEDIDO, 
	C9_ITEM, 
	C9_SEQUEN;

SELECT C9_FILIAL,C9_PEDIDO,C9_CLIENTE,C9_LOJA,A1_NOME,C9_DATENT,C9_ITEM,C9_SEQUEN,C9_PRODUTO,B1_DESC,C9_LOCAL,C9_LOTECTL,COALESCE(DC_LOCALIZ,' ') AS PRD_ENDERE,A1_END AS CLI_ENDERE,A1_MUN,YA_DESCR,CASE WHEN TRIM(C9_NUMSERI) = ' ' THEN DC_NUMSERI ELSE C9_NUMSERI END AS NUMSERI,C9_QTDLIB,C9_QTDLIB * B1_M3 AS VOLUME,CASE WHEN C9_ZCENARI = ' ' AND C9_ZDRIVIN IS NULL THEN 1 WHEN C9_ZCENARI <> ' ' AND C9_ZDRIVIN IS NULL THEN 2 WHEN C9_ZCENARI <> ' ' AND C9_ZDRIVIN IS NOT NULL THEN 2 WHEN C9_ZCENARI = ' ' AND C9_ZDRIVIN IS NOT NULL THEN 4 END AS COMUNIC,C9_DATENT || C9_CLIENTE || C9_PEDIDO || C9_ITEM || C9_SEQUEN AS REC,' ' AS SEL_OK FROM SC9010 C9 INNER JOIN SC5010 C5 ON C9.C9_FILIAL = C5.C5_FILIAL AND C9_PEDIDO = C5_NUM AND C5.D_E_L_E_T_ = ' ' INNER JOIN SB1010 B1 ON B1.B1_FILIAL = ' ' AND B1_COD = C9_PRODUTO AND B1.D_E_L_E_T_ = ' ' INNER JOIN SA1010 A1 ON A1.A1_FILIAL = ' ' AND A1_COD = C9_CLIENTE AND A1.D_E_L_E_T_ = ' ' INNER JOIN SYA010 YA ON YA.YA_FILIAL = ' ' AND YA_CODGI = A1_PAIS AND YA.D_E_L_E_T_ = ' ' LEFT JOIN SDC010 DC ON C9.C9_FILIAL = DC.DC_FILIAL AND DC_PRODUTO = C9_PRODUTO AND C9_LOCAL = DC_LOCAL AND DC_ORIGEM = 'SC6' AND DC_PEDIDO = C9_PEDIDO AND DC_ITEM = C9_ITEM AND DC_SEQ = C9_SEQUEN AND DC_LOTECTL = C9_LOTECTL AND DC_NUMLOTE = C9_NUMLOTE AND DC.D_E_L_E_T_ = ' ' WHERE  C9_FILIAL = '01' AND C9_PEDIDO BETWEEN ' ' AND 'ZZZZZZ' AND C9_CLIENTE BETWEEN ' ' AND 'ZZZZZZ' AND C9_LOJA BETWEEN ' ' AND 'ZZ' AND C9_DATENT BETWEEN '20260811' AND '20491231' AND C9_PRODUTO BETWEEN ' ' AND 'ZZZZZZZZZZZZZZZ' AND C9_BLEST = ' ' AND C9_BLCRED = ' ' AND C9.D_E_L_E_T_ = ' '  ORDER BY  C9_PEDIDO, C9_ITEM, C9_SEQUEN;

----//----

SELECT 
	DAK_ZCENAR, 
FROM 
	DAK990 
WHERE 
	DAK_ZCENAR = '' 
	AND DAK_ZDRVRT = ''; 

----//----

SELECT
	X6_VAR,
	X6_CONTEUD,
	X6_CONTSPA,
	X6_CONTENG
FROM
	SX6010 X6
WHERE
	X6_VAR IN (
		'SU_PSWSEGE',
		'SU_TMAPT',
		'SU_URLSEGE',
		'SU_USRSEGE',
		'SU_DIAPIKE',
		'SU_DIAPIUR',
		'SU_DICENAR',
		'SU_DIORDER',
		'SU_DIRESUL',
		'NX_APTEND'
	);

/*
Criado		SU_PSWSEGE		password
Criado		SU_TMAPT		002
Criado		SU_URLSEGE		http://192.168.0.3:8000/api
Criado		SU_USRSEGE		operador@cliente.com
Criado		SU_DIAPIKE		647fbc3a-9e8d-49b8-ba28-b5ec3d72b673
Alterado	SU_DIAPIUR		https://external.driv.in
Criado		SU_DICENAR		/api/external/v2/scenarios?
Criado		SU_DIORDER		/api/external/v2/orders?
Criado		SU_DIRESUL		/api/external/v2/results?

Criado		NX_APTEND		APT
*/