SELECT TOP 1 
	D3_NUMSEQ 
FROM 
	SD3990  
WHERE 
	D3_FILIAL = '01' 
	AND D3_OP = '000028' 
	AND D3_COD = '000001' 
	AND D3_LOCAL = '01' 
	AND D3_CF = 'PR0' 
ORDER BY 
	R_E_C_N_O_ DESC; 

----//----

SELECT 
	C9_FILIAL, 
	C9_PEDIDO, 
	C9_CLIENTE, 
	C9_LOJA, 
	C5_FECENT AS DTENTREGA, 
	C9_ITEM, 
	C9_SEQUEN, 
	C9_PRODUTO, 
	B1_DESC, 
	C9_LOCAL, 
	C9_LOTECTL, 
	COALESCE(DC_LOCALIZ, '') AS ENDERECO, 
	CASE 
		WHEN TRIM(C9_NUMSERI) = '' THEN DC_NUMSERI ELSE C9_NUMSERI 
	END AS NUMSERI, 
	C9_QTDLIB, 
	C5_FECENT + C9_CLIENTE + C9_PEDIDO + C9_ITEM + C9_SEQUEN AS REC, 
	'' AS SEL_OK 
FROM 
	SC9990 C9 
	INNER JOIN 
		SC5990 C5 
		ON C9.C9_FILIAL = C5.C5_FILIAL 
		AND C9_PEDIDO = C5_NUM 
		AND C5.D_E_L_E_T_ = '' 
	INNER JOIN 
		SB1990 B1 
		ON B1.B1_FILIAL = ' '  
		AND B1_COD = C9_PRODUTO 
		AND B1.D_E_L_E_T_ = '' 
	LEFT JOIN 
		SDC990 DC 
		ON C9.C9_FILIAL = DC.DC_FILIAL 
		AND DC_PRODUTO = DC_PRODUTO 
		AND C9_LOCAL = DC_LOCAL 
		AND DC_ORIGEM = 'SC6' 
		AND DC_PEDIDO = C9_PEDIDO 
		AND DC_ITEM = C9_ITEM 
		AND DC_SEQ = C9_SEQUEN 
		AND DC_LOTECTL = C9_LOTECTL 
		AND DC_NUMLOTE = C9_NUMLOTE 
		AND DC.D_E_L_E_T_ = '' 
WHERE 
	C9_PEDIDO BETWEEN '      ' AND 'ZZZZZZ' 
	AND C9_CLIENTE BETWEEN '      ' AND 'ZZZZZZ' 
	AND C9_LOJA BETWEEN '  ' AND 'ZZ' 
	AND C5_FECENT BETWEEN '20260601' AND '20300729' 
	AND C9_PRODUTO BETWEEN '               ' AND 'ZZZZZZZZZZZZZZZ' 
	AND C9_BLEST = '' 
	AND C9_BLCRED = '' 
	AND C9.D_E_L_E_T_ = '' 
ORDER BY 
	C9_PEDIDO, 
	C9_ITEM, 
	C9_SEQUEN; 

----//----